DATA_FOLDER = ".data"

EMBEDDING_FILE = "embeddings.npy"
EMBEDDING_PATH = f"{DATA_FOLDER}/{EMBEDDING_FILE}"

FILENAME_FILE = "filenames.txt"
FILENAME_PATH = f"{DATA_FOLDER}/{FILENAME_FILE}"

FAISS_INDEX_FILE = "index.faiss"
FAISS_INDEX_PATH = f"{DATA_FOLDER}/{FAISS_INDEX_FILE}"

META_DATA_FILE = "metadata.db"
META_DATA_PATH = f"{DATA_FOLDER}/{META_DATA_FILE}"